### ISSUE TITLE
is this production ready?

### ISSUE THREAD

**Issue by sprappcom** [nurmohammed840/frpc#3]
as titled, who are the users of this?

can u show a side by side performance benchmark with numbers for frpc vs grpc etc?

**Comment by nurmohammed840** [comment]
> Is this production ready ?

I am using this on some of my projects, I didn't find any bugs as of today, But It still require more testing (specially on client codegen side), So please find some bugs and report it.

> as titled, who are the users of this?

I didn't published it yet, So I believe, No one, but me.

> can u show a side by side performance benchmark with numbers for frpc vs gRPC etc?

Performance benefit come from data serialization, It use [databuf](https://github.com/nurmohammed840/databuf.rs), It didn't write any benchmark, but It should be faster compare to gRPC protobuf. If you write some benchmark, let me know the results.

For RPC performance, You can't compare it with gRPC, Because unlike gRPC, It is transport independent. So you can create you own fastest [transport](https://github.com/nurmohammed840/frpc/blob/main/frpc/transport-core/src/lib.rs) using faster  protocol, like (HTTP/3, [QUIC](https://github.com/quinn-rs/quinn), [WebSocket](https://github.com/nurmohammed840/websocket.rs), ...)

> Note: The name (frpc) for this library is not finalized yet, It will change.

**Comment by nurmohammed840** [comment]
Here is a simple (in memory)  [rpc benchmark](https://github.com/nurmohammed840/frpc/blob/main/examples/bench.rs).

[Result](https://github.com/nurmohammed840/frpc/actions/runs/9734736194/job/26863115866): 

```
Normal: 171.838193ms
RPC: 167.165196ms
```
